import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  containerDark: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    alignItems: 'center',
    backgroundColor: '#121212',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  icon: {
    position: 'absolute',
    top: 40,
    right: 20,
    backgroundColor: 'white',
    padding: 10,
    borderRadius: 50,
  },
  iconDark: {
    position: 'absolute',
    top: 40,
    right: 20,
    backgroundColor: '#1E1E1E',
    padding: 10,
    borderRadius: 50,
  },
  modalContainer: {
    height: '100%',
    width: '100%',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContainerDark: {
    height: '100%',
    width: '100%',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.5)',
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: 'white',
  },
  listItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    padding: 10,
    marginVertical: 5,
    width: '90%',
    alignSelf: 'center',
    borderRadius: 5,
    flexWrap: 'wrap',
  },
  listItemDark: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.8)',
    padding: 10,
    marginVertical: 5,
    width: '90%',
    alignSelf: 'center',
    borderRadius: 5,
    flexWrap: 'wrap',
  },
  listItemText: {
    fontSize: 16,
  },
  listItemTextDark: {
    fontSize: 16,
    color: 'white',
  },
  drawingButtons: {
    position: 'absolute',
    top: 40,
    right: 20,
    flexDirection: 'row',
  },
  finishButton: {
    backgroundColor: 'red',
    padding: 10,
    borderRadius: 5,
    marginLeft: 10,
    alignItems: 'center',
  },
  finishButtonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  cancelButton: {
    backgroundColor: 'gray',
    padding: 10,
    borderRadius: 5,
  },
  cancelButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    backgroundColor: '#375B81B7',
    padding: 10,
    marginRight: 10,
    borderRadius: 5,
    textAlign: 'center',
    marginVertical: 5,
  },
  finishBtn: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    backgroundColor: '#BE2F2A',
    padding: 10,
    marginRight: 10,
    borderRadius: 5,
    textAlign: 'center',
    marginVertical: 5,
  },
  nameModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  nameModalContainerDark: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.5)',
  },
  textInput: {
    height: 45,
    borderColor: 'gray',
    borderWidth: 1,
    backgroundColor: 'white',
    paddingHorizontal: 10,
    marginBottom: 20,
    width: '80%',
    borderRadius: 7,
  },
  textInputDark: {
    height: 45,
    borderColor: 'gray',
    borderWidth: 1,
    backgroundColor: '#333',
    paddingHorizontal: 10,
    marginBottom: 20,
    width: '80%',
    borderRadius: 7,
  },
  buttonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    backgroundColor: '#007BFF',
    padding: 10,
    borderRadius: 5,
    textAlign: 'center',
    marginVertical: 5,
  },
  deleteButton: {
    color: 'white',
    fontSize: 16,
    backgroundColor: '#FF0000',
    padding: 5,
    borderRadius: 5,
    textAlign: 'center',
    marginTop: 5,
  },
  namingButtons: {
    flexDirection: 'row',
  },
  marker: {
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    padding: 5,
    borderRadius: 5,
    borderColor: '#ccc',
    borderWidth: 1,
  },
  text: {
    color: '#000',
    fontSize: 13,
    textAlign: 'center',
  },
});

export default styles;
